// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj6lVG5FwWMggD00hNwj8_6fi9raNLeMM',
    appId: '1:240719643734:web:574350757a0c34085ca7f7',
    messagingSenderId: '240719643734',
    projectId: 'event-app-2d914',
    authDomain: 'event-app-2d914.firebaseapp.com',
    storageBucket: 'event-app-2d914.appspot.com',
    measurementId: 'G-MSJRCKD679',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXkry83xccUenBUdHaMUOwmfTCLbfeuU',
    appId: '1:240719643734:android:9f43f0df1209d7cc5ca7f7',
    messagingSenderId: '240719643734',
    projectId: 'event-app-2d914',
    storageBucket: 'event-app-2d914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLD3LThX854l7j13A_2IHmCXqK7uZN4_M',
    appId: '1:240719643734:ios:3248df6567cec73a5ca7f7',
    messagingSenderId: '240719643734',
    projectId: 'event-app-2d914',
    storageBucket: 'event-app-2d914.appspot.com',
    iosClientId: '240719643734-ovf92pld6cm7b7egem6v6rk6krfbm5ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );
}
